# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e5c572d0e15ac7bcbd093f00b81651a2bd6df7063f848627e5d6df29c35513da7bcd18d5d051c032355528d89f0681b1fed01019d3163b8e4615e601b029304

test:
  secret_key_base: 540ae24bf7123394ffedb22de54c64ad5e9402b556ac1bf8e370e611b7e4e9efc4042c69baaf2679607cf2e6286d11d71f31c875a96ea047272f1cf5d6d79a76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
